apiVersion: apps/v1
kind: Deployment
metadata:
  {{- template "app.metadata" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }} # Use nindent instead of indent
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }} # Use nindent instead of indent
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: 804756348441.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}:{{ .Values.imageTag }}
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
